FROM ubuntu:18.04 AS hipr_container
#FROM node:8 AS hipr_container

RUN apt-get -qq update >> /dev/null
RUN apt-get install -qq -y wget git automake libtool unzip build-essential mesa-common-dev >> /dev/null

RUN apt-get install nodejs npm -y --fix-missing

ADD ./hipr-setup.sh /root/hipr-setup.sh

RUN chmod +x /root/hipr-setup.sh
RUN bash /root/hipr-setup.sh local /root/files /root/build
